name: Docker Image CI - Bluetooth

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the full Docker image
      run: docker build . --file bluetooth.docker --tag rfswift_bluetooth:$(date +%s)
