name: Docker Image CI - Reversing

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Build the core image
      run: docker build . --file Dockerfiles/SDR/corebuild.docker --tag corebuild:latest
    
    - name: Build the Reversing Docker image
      run: docker build . --file Dockerfiles/reversing.docker --tag rfswift_reversing:$(date +%s)
