name: Docker Image CI - RFID

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Build the core image
      run: docker build . --file Dockerfiles/SDR/corebuild.docker --tag corebuild:latest
    
    - name: Build the full Docker image
      run: docker build . --file Dockerfiles/rfid.docker --tag rfswift_rfid:$(date +%s)
