name: Docker Image CI - SDR full

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the core image
      run: docker build . --file Dockerfiles/SDR/corebuild.docker --tag corebuild:latest

    - name: Build the light stage for SDR
      run: docker build . --file Dockerfiles/SDR/sdr_light.docker --tag sdr_light:latest

    - name: Build the full SDR image (stage 1)
      run: docker build . --file Dockerfiles/SDR/sdr_full.docker --target extraoot --tag sdr_full_stage1:latest

    - name: Build the full SDR image (stage 2)
      run: docker build . --file Dockerfiles/SDR/sdr_full.docker --target extrasofts --tag sdr_full_stage2:latest
