name: Docker Image CI - Wi-Fi

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the full Docker image
      run: docker build . --file wifi.docker --tag rfswift_wifi:$(date +%s)
